;===============================================================================
; AUTO-GENERATED by tools/hint_room_voice_sync.py -- DO NOT EDIT
; voice_pipeline_v18.py用の音声生成専用シナリオ。ゲームからは実行しない。
;===============================================================================

*topic_ending
; 18 voices
#mahoru
[voice id="hr_topic_ending_001"]
犯人を見つけたのに、まだ見ていない結末があるみたいなんです。[p]

#maicro
[voice id="hr_topic_ending_002"]
人の事件が片づいても、館まで素直に口を開くとは限らないよ。[p]

#mahoru
[voice id="hr_topic_ending_003"]
館にも事情聴取が必要なんですか？[p]

#maicro
[voice id="hr_topic_ending_004"]
しかも黙秘が得意でね。事件の外に置かれたものを見直してごらん。[p]

#maicro
[voice id="hr_topic_ending_005"]
別の結末を望むなら、最後の推理より、事件が起きる前の歩き方を疑うべきだ。[p]

#mahoru
[voice id="hr_topic_ending_006"]
事件の前？　結末を分けるのは、最後の推理じゃないんですか。[p]

#maicro
[voice id="hr_topic_ending_007"]
夜に必要な問いは、明るいうちでなければ育たないものさ。[p]

#mahoru
[voice id="hr_topic_ending_008"]
夜になってから帳尻を合わせようとしても遅い？[p]

#maicro
[voice id="hr_topic_ending_009"]
館の時計は案外せっかちでね。日が落ちるころには、開かなくなる扉もある。[p]

#mahoru
[voice id="hr_topic_ending_010"]
『日暮れまでに全部集めろ』ではないんですね。[p]

#maicro
[voice id="hr_topic_ending_011"]
集めるのではなく、誰がなぜ来たのかを気にしておく。[p]

#maicro
[voice id="hr_topic_ending_012"]
そして、この館が見せる形と、隠したがる形の違いを覚えておく。[p]

#mahoru
[voice id="hr_topic_ending_013"]
人と建物、両方の事情を考える。[p]

#maicro
[voice id="hr_topic_ending_014"]
そう。事件の証拠だけを追うと、事件の外にある扉を見失う。[p]

#mahoru
[voice id="hr_topic_ending_015"]
苦い結末を見た後でも、やり直せますか？[p]

#maicro
[voice id="hr_topic_ending_016"]
もちろん。結末は行き止まりではなく、次に見る場所を照らす街灯だよ。[p]

#mahoru
[voice id="hr_topic_ending_017"]
街灯にしては、だいぶ暗かったですけど。[p]

#maicro
[voice id="hr_topic_ending_018"]
だから相談所を建てた。照明費は出ないがね。[p]

*topic_true_end
; 20 voices
#mahoru
[voice id="hr_topic_true_end_001"]
舞黒さん。今日は真エンディングへの行き方を、もう少しぶっちゃけてください。[p]

#maicro
[voice id="hr_topic_true_end_002"]
名前からして、ずいぶん答えに近い相談だね。[p]

#mahoru
[voice id="hr_topic_true_end_003"]
答えそのものではなく、昼と夜に何を残せばいいかだけ。[p]

#maicro
[voice id="hr_topic_true_end_004"]
なら、昼は事件を追う時間ではない。館が隠している道具と入口を探す時間だ。[p]

#mahoru
[voice id="hr_topic_true_end_005"]
道具と入口？[p]

#maicro
[voice id="hr_topic_true_end_006"]
談話室の古い声を聞き流さないこと。四つの数字は、もっと高い場所の陽だまりで役に立つ。[p]

#mahoru
[voice id="hr_topic_true_end_007"]
数字で開くものの中に、館の形を知る手掛かりがある。[p]

#maicro
[voice id="hr_topic_true_end_008"]
もう一つ。館に散った三つの色は、重ねて初めて命令になる。読めたら、机は正面から眺めるものだという常識を捨てる。[p]

#mahoru
[voice id="hr_topic_true_end_009"]
上、横、それでもなければ……裏側。[p]

#maicro
[voice id="hr_topic_true_end_010"]
その二つを手にしたら、古い模型と今の部屋の奥行きを比べる。合わない場所には理由がある。[p]

#mahoru
[voice id="hr_topic_true_end_011"]
見つけるだけじゃなく、夕食前に中まで入っておく。[p]

#maicro
[voice id="hr_topic_true_end_012"]
そう。それが昼の宿題だ。ついでに、遠くから来た客が何を探しているのか聞ければ申し分ない。[p]

#mahoru
[voice id="hr_topic_true_end_013"]
夜は？[p]

#maicro
[voice id="hr_topic_true_end_014"]
夜は毒だけを追わないこと。昼に転んだ執務室の椅子を、ただの思い出で終わらせない。[p]

#mahoru
[voice id="hr_topic_true_end_015"]
椅子の周りに、昔の人たちを結ぶ記録が残っている。[p]

#maicro
[voice id="hr_topic_true_end_016"]
そして一階の陽だまりへ戻る。Aなら床の痕跡、Bなら植物の足元を調べた、その先だ。[p]

#mahoru
[voice id="hr_topic_true_end_017"]
毒の手掛かりを見つけて満足せず、床そのものをもう一度見る。[p]

#maicro
[voice id="hr_topic_true_end_018"]
昼に地下書斎へ入っていれば、今度は別の入口が君に見つけられる。[p]

#mahoru
[voice id="hr_topic_true_end_019"]
昼に館の道具と隠し部屋。夜に古い記録ともう一つの地下。客の目的も忘れない。[p]

#maicro
[voice id="hr_topic_true_end_020"]
そこまで揃えて事件を解けば、館のほうから続きを話し始めるよ。これ以上は本当に答えだ。[p]

*topic_route
; 18 voices
#mahoru
[voice id="hr_topic_route_001"]
前と違うルートへ行きたいんです。[p]

#maicro
[voice id="hr_topic_route_002"]
道に迷ったのかい？[p]

#mahoru
[voice id="hr_topic_route_003"]
システム上の話です。[p]

#maicro
[voice id="hr_topic_route_004"]
庭では、どこへ行ったかより、いつ遠回りしたかが後まで響く。[p]

#maicro
[voice id="hr_topic_route_005"]
分かれ道は、目の前に標識が出るとは限らない。[p]

#mahoru
[voice id="hr_topic_route_006"]
気づかないうちに選んでいる？[p]

#maicro
[voice id="hr_topic_route_007"]
午後の庭で、何を見てから散策へ向かったか。そこから考えるといい。[p]

#mahoru
[voice id="hr_topic_route_008"]
場所より、順番を見る。[p]

#maicro
[voice id="hr_topic_route_009"]
そう。君が動く時刻が変われば、他の人が館を出入りする時刻も変わる。[p]

#mahoru
[voice id="hr_topic_route_010"]
人の予定がずれると、事件の準備もずれる。[p]

#maicro
[voice id="hr_topic_route_011"]
使える部屋、手に取れる道具、残る痕跡。どれも少しずつ変わる。[p]

#mahoru
[voice id="hr_topic_route_012"]
犯人が変わるわけではないんですよね。[p]

#maicro
[voice id="hr_topic_route_013"]
役者は同じでも、舞台装置が違えば芝居は変わる。[p]

#mahoru
[voice id="hr_topic_route_014"]
まず庭での自分の行動順を比べてみる。[p]

#maicro
[voice id="hr_topic_route_015"]
同じ選択を繰り返すより、散策へ向かうまでの寄り道を変えてごらん。[p]

#mahoru
[voice id="hr_topic_route_016"]
一個ずつ試すしかないんですか？[p]

#maicro
[voice id="hr_topic_route_017"]
探偵は比較が仕事だよ。総当たりと言うと急に格好が悪くなるがね。[p]

#mahoru
[voice id="hr_topic_route_018"]
言い換えても総当たりは総当たりです。[p]

*topic_stop
; 18 voices
#mahoru
[voice id="hr_topic_stop_001"]
あの場面、すぐ動いたら間に合わなかったんです。[p]

#maicro
[voice id="hr_topic_stop_002"]
人を救おうとして、誰より早く動きたい時はある。[p]

#maicro
[voice id="hr_topic_stop_003"]
けれど、勇気と早撃ちは別物だよ。[p]

#mahoru
[voice id="hr_topic_stop_004"]
早く選べばいいわけじゃない……？[p]

#maicro
[voice id="hr_topic_stop_005"]
あの場面では、君の手より先に、全員の視線がどこへ向いているかを見る。[p]

#mahoru
[voice id="hr_topic_stop_006"]
助けたい人ではなく、見ている人？[p]

#maicro
[voice id="hr_topic_stop_007"]
動けば止められるのか。動くことで、誰かの判断を早めてしまわないか。[p]

#mahoru
[voice id="hr_topic_stop_008"]
行動の速さではなく、きっかけの順番を考える。[p]

#maicro
[voice id="hr_topic_stop_009"]
そう。何もしない時間にも、場面を変える働きがある。[p]

#mahoru
[voice id="hr_topic_stop_010"]
待っているだけで状況が良くなるとは思えません。[p]

#maicro
[voice id="hr_topic_stop_011"]
待つ目的は安全になることではない。視線と立ち位置が変わる瞬間を見つけることだ。[p]

#mahoru
[voice id="hr_topic_stop_012"]
その瞬間が来たら、手元を見直す。[p]

#maicro
[voice id="hr_topic_stop_013"]
道具の名前に用途を決めさせないこと。探偵の持ち物は、説明書より融通が利く。[p]

#mahoru
[voice id="hr_topic_stop_014"]
また行儀の悪い案を勧めていますね。[p]

#maicro
[voice id="hr_topic_stop_015"]
行儀よく失敗するよりはいい。[p]

#mahoru
[voice id="hr_topic_stop_016"]
まず、誰が誰を見ているか。次に、待つと何が変わるか。[p]

#maicro
[voice id="hr_topic_stop_017"]
そこまで考えれば、君自身の案が出るはずだ。[p]

#mahoru
[voice id="hr_topic_stop_018"]
出なかったら、また相談に来ます。[p]

*topic_scene7
; 18 voices
#mahoru
[voice id="hr_topic_scene7_001"]
零度警部の信頼を得ると、捜査が有利になるんですか？[p]

#maicro
[voice id="hr_topic_scene7_002"]
信頼は時間をくれるものではない。迷わない時間と交換するものだよ。[p]

#mahoru
[voice id="hr_topic_scene7_003"]
得したのか損したのか、もう怪しいんですけど。[p]

#maicro
[voice id="hr_topic_scene7_004"]
信を得た探偵は少し遅れて歩き出す代わりに、警部の見立てをひとつ持っている。[p]

#maicro
[voice id="hr_topic_scene7_005"]
道に迷えば、次に見るべき部屋も何度でも相談できる。[p]

#mahoru
[voice id="hr_topic_scene7_006"]
信頼されなかった場合は？[p]

#maicro
[voice id="hr_topic_scene7_007"]
早く放り出される。ただし居間は、しばらく警察のものだ。[p]

#mahoru
[voice id="hr_topic_scene7_008"]
純粋な上位互換ではないんですね。[p]

#maicro
[voice id="hr_topic_scene7_009"]
早さを取るか、道しるべを取るか。普通に話せたなら、その中間だよ。[p]

#mahoru
[voice id="hr_topic_scene7_010"]
信頼は単純なボーナスではなく、探索の形を変える。[p]

#maicro
[voice id="hr_topic_scene7_011"]
その通り。まず、開始時に何を知っているか、どの部屋が開いているかを比べる。[p]

#mahoru
[voice id="hr_topic_scene7_012"]
時計だけを見て、得した損したと決めない。[p]

#maicro
[voice id="hr_topic_scene7_013"]
情報があれば無駄足を減らせる。自由があれば、先に別の場所へ行ける。[p]

#mahoru
[voice id="hr_topic_scene7_014"]
自分が迷いやすいなら、信頼が助けになる。[p]

#maicro
[voice id="hr_topic_scene7_015"]
地図を覚えているなら、早く動けることが助けになるかもしれない。[p]

#mahoru
[voice id="hr_topic_scene7_016"]
零度警部に嫌われる攻略を勧めてません？[p]

#maicro
[voice id="hr_topic_scene7_017"]
勧めてはいないよ。人間関係まで最短化すると、食事会で席がなくなる。[p]

#mahoru
[voice id="hr_topic_scene7_018"]
それは普通に困ります。[p]

*topic_chat
; 18 voices
#mahoru
[voice id="hr_topic_chat_001"]
ヒントではなく、舞黒さん自身の話を聞いてもいいですか？[p]

#maicro
[voice id="hr_topic_chat_002"]
私の話かい。困ったな、嬉しいな。では茶を淹れよう。[p]

#mahoru
[voice id="hr_topic_chat_003"]
さっきから一杯も出てきていませんけど。[p]

#maicro
[voice id="hr_topic_chat_004"]
死んでから一番不便なのは、茶を飲めないことではない。淹れられないことだよ。[p]

#mahoru
[voice id="hr_topic_chat_005"]
この館で一番好きな場所は？[p]

#maicro
[voice id="hr_topic_chat_006"]
客のいる部屋だね。館は人を迎えて、ようやく館になる。[p]

#mahoru
[voice id="hr_topic_chat_007"]
資料室ではないんですか？[p]

#maicro
[voice id="hr_topic_chat_008"]
資料室は好きだが、模型をあれほど大きくした覚えはないよ。[p]

#mahoru
[voice id="hr_topic_chat_009"]
館主公認ではなかった。[p]

#maicro
[voice id="hr_topic_chat_010"]
次に建てる時は、もう少し小さくするよう言っておこう。[p]

#mahoru
[voice id="hr_topic_chat_011"]
次がある言い方をしないでください。[p]

#mahoru
[voice id="hr_topic_chat_012"]
舞黒さんは、客が帰った後は何をしていたんですか？[p]

#maicro
[voice id="hr_topic_chat_013"]
昔なら片づけだね。今は片づけられないので、散らかったまま眺める。[p]

#mahoru
[voice id="hr_topic_chat_014"]
幽霊って、意外と手持ち無沙汰なんですね。[p]

#maicro
[voice id="hr_topic_chat_015"]
だから相談所はありがたい。君が来ると、館の時計が少し賑やかになる。[p]

#mahoru
[voice id="hr_topic_chat_016"]
画面まで賑やかになりすぎる時がありますけど。[p]

#maicro
[voice id="hr_topic_chat_017"]
それは別の相談項目にしておいた。[p]

#mahoru
[voice id="hr_topic_chat_018"]
館主が不具合を仕様にしました。[p]

*topic_dev
; 20 voices
#maicro
[voice id="hr_topic_dev_001"]
これは館の設計図ではないね。『仕様書』と書いてある。[p]

#mahoru
[voice id="hr_topic_dev_002"]
館主が読んではいけない種類の資料です。[p]

#maicro
[voice id="hr_topic_dev_003"]
同じ一日を歩き直しても、違う発見になるよう順番を組んだらしい。[p]

#mahoru
[voice id="hr_topic_dev_004"]
いきなり核心に近い開発裏話を読むの、やめてもらえます？[p]

#maicro
[voice id="hr_topic_dev_005"]
零度警部の信頼も、単純なご褒美にはしなかったそうだ。[p]

#maicro
[voice id="hr_topic_dev_006"]
信じられれば情報が増える。信じられなければ、先に動ける。[p]

#mahoru
[voice id="hr_topic_dev_007"]
人間関係をタイムアタックに使わないでください。[p]

#maicro
[voice id="hr_topic_dev_008"]
失敗も後の会話へ持ち越す。探偵の見落としも、物語には立派な発見なのさ。[p]

#mahoru
[voice id="hr_topic_dev_009"]
少し綺麗にまとめて、誤魔化しましたね？[p]

#mahoru
[voice id="hr_topic_dev_010"]
この仕様書、選択に正解と不正解を付けないと書いてあります。[p]

#maicro
[voice id="hr_topic_dev_011"]
その瞬間に気づいたことを、後の会話へ持ち越すためだそうだ。[p]

#mahoru
[voice id="hr_topic_dev_012"]
失敗も分岐の材料になる？[p]

#maicro
[voice id="hr_topic_dev_013"]
正解するまで戻すと、探偵が迷った時間まで物語から消えてしまう。[p]

#mahoru
[voice id="hr_topic_dev_014"]
私の立ち尽くした時間まで保存されているんですね。[p]

#maicro
[voice id="hr_topic_dev_015"]
作者は探偵より執念深いらしい。[p]

#mahoru
[voice id="hr_topic_dev_016"]
聞き捨てならない情報が出ました。[p]

#maicro
[voice id="hr_topic_dev_017"]
安心して。館主も勝手に黒塗りやドットにされる。[p]

#mahoru
[voice id="hr_topic_dev_018"]
開発資料への苦情窓口はどこです？[p]

#maicro
[voice id="hr_topic_dev_019"]
今、君が座っているところだよ。[p]

#mahoru
[voice id="hr_topic_dev_020"]
受付担当が当事者なんですけど。[p]

*topic_unstable
; 20 voices
#mahoru
[voice id="hr_topic_unstable_001"]
相談所の画面が時々、まったく違う姿になるんですけど。[p]

#maicro
[voice id="hr_topic_unstable_002"]
館も長く生きると、たまには模様替えをしたくなる。[p]

#mahoru
[voice id="hr_topic_unstable_003"]
黒塗りやドット絵や配信になる模様替えがあります？[p]

#maicro
[voice id="hr_topic_unstable_004"]
流行に敏感な館だろう。[p]

#mahoru
[voice id="hr_topic_unstable_005"]
幽霊がVTuberを始める流行は知りません。[p]

#maicro
[voice id="hr_topic_unstable_006"]
肉体がないという点では、適性が高いと思わないかい？[p]

#mahoru
[voice id="hr_topic_unstable_007"]
そこだけ妙に説得力を出さないでください。[p]

#maicro
[voice id="hr_topic_unstable_008"]
心配しなくても、話題を選ぶ画面は動かないよ。[p]

#mahoru
[voice id="hr_topic_unstable_009"]
会話を始めた後だけ不安定になる？[p]

#maicro
[voice id="hr_topic_unstable_010"]
そう。話を始める瞬間に、館がたまにくしゃみをする。[p]

#mahoru
[voice id="hr_topic_unstable_011"]
くしゃみで解像度が落ちる館、初めて見ました。[p]

#maicro
[voice id="hr_topic_unstable_012"]
どの姿になっても、相談の中身までは変わらない。[p]

#mahoru
[voice id="hr_topic_unstable_013"]
黒塗りになると怖さは三割増しです。[p]

#maicro
[voice id="hr_topic_unstable_014"]
顔が見えないぶん、想像力で補えるだろう？[p]

#mahoru
[voice id="hr_topic_unstable_015"]
配信ではコメント欄まで勝手に増えています。[p]

#maicro
[voice id="hr_topic_unstable_016"]
館の壁まで視聴者として数えているからね。[p]

#mahoru
[voice id="hr_topic_unstable_017"]
修理する予定は？[p]

#maicro
[voice id="hr_topic_unstable_018"]
不具合ではなく、低確率の余興として保存することにした。[p]

#mahoru
[voice id="hr_topic_unstable_019"]
言い方だけで修理を終えましたね。[p]

#maicro
[voice id="hr_topic_unstable_020"]
館主の権限は便利だろう？[p]

*intro_silhouette
; 3 voices
#mahoru
[voice id="hr_intro_silhouette_001"]
……舞黒さん。今日、輪郭しか見えないんですけど。[p]

#maicro
[voice id="hr_intro_silhouette_002"]
秘密を守る相談所らしいだろう？[p]

#mahoru
[voice id="hr_intro_silhouette_003"]
相談員まで秘密にしないでください。[p]

*intro_pixel
; 3 voices
#mahoru
[voice id="hr_intro_pixel_001"]
なんか今日は、全体的にかくかくしていません？[p]

#maicro
[voice id="hr_intro_pixel_002"]
ヒントはぼかすものだからね。解像度もぼかしてみた。[p]

#mahoru
[voice id="hr_intro_pixel_003"]
別のものまでぼかさないでください。[p]

*intro_vtuber
; 4 voices
#mahoru
[voice id="hr_intro_vtuber_001"]
……どうして私が『ツッコミ担当』と表示されてるんですか？[p]

#maicro
[voice id="hr_intro_vtuber_002"]
配信者がボケる以上、必要な役職だよ。[p]

#mahoru
[voice id="hr_intro_vtuber_003"]
まず配信者になった経緯を説明してください。[p]

#maicro
[voice id="hr_intro_vtuber_004"]
偶然だ。カメラも偶然、投げ銭ボタンも偶然だよ。[p]

*bad_end
; 4 voices
#mahoru
[voice id="hr_bad_end_001"]
ここへ来られたということは、一度は結末を見届けたんですよね。[p]

#maicro
[voice id="hr_bad_end_002"]
たとえ苦い結末でも、ここでは失敗とは呼ばないよ。[p]

#mahoru
[voice id="hr_bad_end_003"]
では、何と呼ぶんです？[p]

#maicro
[voice id="hr_bad_end_004"]
次へ持っていく質問票さ。反省文より、ずっと役に立つ。[p]
